elasticsearch:
  imageTag: 7.11.1
  service:
    type: ClusterIP
  antiAffinity: soft
  persistence: 
    enabled: false

  replicas: 2

  ingress:
    enabled: false

kibana:
  imageTag: 7.11.1
  service:
    type: ClusterIP
  kibanaConfig:
    kibana.yml: |
      server.defaultRoute: /test/kibana
      uiSettings.overrides.defaultRoute: /test/kibana


ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"

environnement: example