- hosts: master
  user: administrateur
  roles:
    - elastic.elasticsearch
  vars:
    es_version: 7.11.1
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "master"
      cluster.name: "cluster"
      network.host: "0.0.0.0"
      cluster.initial_master_nodes: ["master","master-data"]
      discovery.seed_hosts:  ["master.elastic-cluster.com:9300","master-data.elastic-cluster.com:9300"]
      http.port: 9200
      transport.port: 9300
      node.data: false
      node.master: true

- hosts: master-data
  user: administrateur
  roles:
    - elastic.elasticsearch
  vars:
    es_version: 7.11.1
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "master-data"
      cluster.name: "cluster"
      network.host: "0.0.0.0"
      cluster.initial_master_nodes: ["master","master-data"]
      discovery.seed_hosts:  ["master.elastic-cluster.com:9300","master-data.elastic-cluster.com:9300"]
      http.port: 9200
      transport.port: 9300
      node.data: true
      node.master: true

- hosts: data
  user: administrateur
  roles:
    - elastic.elasticsearch
  vars:
    es_version: 7.11.1
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "data"
      cluster.name: "cluster"
      network.host: "0.0.0.0"
      cluster.initial_master_nodes: ["master","master-data"]
      discovery.seed_hosts:  ["master.elastic-cluster.com:9300","master-data.elastic-cluster.com:9300"]
      http.port: 9200
      transport.port: 9300
      node.data: true
      node.master: false

- hosts: kibana
  user: administrateur
  become: yes
  roles:
    - geerlingguy.kibana
  vars:
    kibana_elasticsearch_url: '["http://master.elastic-cluster.com:9200","http://master-data.elastic-cluster.com:9200"]'
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_version: "7.x"
    kibana_config_file_path: /etc/kibana/kibana.yml