imageTag: 7.11.1
service:
  type: LoadBalancer
antiAffinity: soft
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
persistence: 
  enabled: false

replicas: 3